### ISSUE TITLE
Komentář

### ISSUE THREAD

**Issue by Amatthe** [Czechitas-Koderka-podklady/PROJEKT-Vizitka#3]
Ahoj,
poprvé to trochu nevyšlo, GitHub mě zmátnul absencí tlačítka Issues. Nonic, tak znova: tvoje řešení jako by z oka vypadlo zadání. Super práce, jen tak dál!

**Comment by Amatthe** [comment]
Já se z toho... Omlouvám se, GitHub mě neskutečným způsobem mate ._.

**Comment by lrolecek** [comment]
S dovolením zavřu tohle "issue" jako vyřešené :)
